name: Build & Publish Docker Image to GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the image
        run: |
          docker login --username sandeep84 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/sandeep84/next-cash:latest
      - name: Push the image
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/sandeep84/next-cash:latest
